import { Block } from "../Block";
import { BlockBloodStone } from "../BlockBloodStone";
import { BlockBookshelf } from "../BlockBookshelf";
import { BlockButton } from "../BlockButton";
import { BlockCactus } from "../BlockCactus";
import { BlockCake } from "../BlockCake";
import { BlockChest } from "../BlockChest";
import { BlockClay } from "../BlockClay";
import { BlockCloth } from "../BlockCloth";
import { BlockCrops } from "../BlockCrops";
import { BlockDirt } from "../BlockDirt";
import { BlockDispenser } from "../BlockDispenser";
import { BlockDoor } from "../BlockDoor";
import { BlockFence } from "../BlockFence";
import { BlockFire } from "../BlockFire";
import { BlockFlower } from "../BlockFlower";
import { BlockFlowing } from "../BlockFlowing";
import { BlockFurnace } from "../BlockFurnace";
import { BlockGlass } from "../BlockGlass";
import { BlockGrass } from "../BlockGrass";
import { BlockGravel } from "../BlockGravel";
import { BlockIce } from "../BlockIce";
import { BlockJukeBox } from "../BlockJukeBox";
import { BlockLadder } from "../BlockLadder";
import { BlockLeaves } from "../BlockLeaves";
import { BlockLever } from "../BlockLever";
import { BlockLightStone } from "../BlockLightStone";
import { BlockLog } from "../BlockLog";
import { BlockMinecartTrack } from "../BlockMinecartTrack";
import { BlockMobSpawner } from "../BlockMobSpawner";
import { BlockMushroom } from "../BlockMushroom";
import { BlockNote } from "../BlockNote";
import { BlockObsidian } from "../BlockObsidian";
import { BlockOre } from "../BlockOre";
import { BlockOreBlock } from "../BlockOreBlock";
import { BlockPortal } from "../BlockPortal";
import { BlockPressurePlate } from "../BlockPressurePlate";
import { BlockPumpkin } from "../BlockPumpkin";
import { BlockRedstoneOre } from "../BlockRedstoneOre";
import { BlockRedstoneTorch } from "../BlockRedstoneTorch";
import { BlockRedstoneWire } from "../BlockRedstoneWire";
import { BlockReed } from "../BlockReed";
import { BlockSand } from "../BlockSand";
import { BlockSandStone } from "../BlockSandStone";
import { BlockSapling } from "../BlockSapling";
import { BlockSign } from "../BlockSign";
import { BlockSlowSand } from "../BlockSlowSand";
import { BlockSnow } from "../BlockSnow";
import { BlockSnowBlock } from "../BlockSnowBlock";
import { BlockSoil } from "../BlockSoil";
import { BlockSponge } from "../BlockSponge";
import { BlockStairs } from "../BlockStairs";
import { BlockStationary } from "../BlockStationary";
import { BlockStep } from "../BlockStep";
import { BlockStone } from "../BlockStone";
import { BlockTNT } from "../BlockTNT";
import { BlockTorch } from "../BlockTorch";
import { BlockWorkbench } from "../BlockWorkbench";
import { EntityItem } from "../EntityItem";
import { EnumMobType } from "../EnumMobType";
import { Item } from "../Item";
import { ItemBlock } from "../ItemBlock";
import { ItemCloth } from "../ItemCloth";
import { ItemLog } from "../ItemLog";
import { ItemStack } from "../ItemStack";
import { MaterialRegistry } from "./MaterialRegistry";

export class BlockRegistry {
	static {
		Block.stone = (new  BlockStone(1, 1)).setHardness(1.5).setResistance(10.0).setStepSound(Block.soundStoneFootstep).setBlockName("stone");
		Block.grass = (new  BlockGrass(2)).setHardness(0.6).setStepSound(Block.soundGrassFootstep).setBlockName("grass") as BlockGrass;
		Block.dirt = (new  BlockDirt(3, 2)).setHardness(0.5).setStepSound(Block.soundGravelFootstep).setBlockName("dirt");
		Block.cobblestone = (new  Block(4, 16, MaterialRegistry.rock)).setHardness(2.0).setResistance(10.0).setStepSound(Block.soundStoneFootstep).setBlockName("stonebrick");
		Block.planks = (new  Block(5, 4, MaterialRegistry.wood)).setHardness(2.0).setResistance(5.0).setStepSound(Block.soundWoodFootstep).setBlockName("wood");
		Block.sapling = (new  BlockSapling(6, 15)).setHardness(0.0).setStepSound(Block.soundGrassFootstep).setBlockName("sapling");
		Block.bedrock = (new  Block(7, 17, MaterialRegistry.rock)).setHardness(-1.0).setResistance(6000000.0).setStepSound(Block.soundStoneFootstep).setBlockName("bedrock");
		Block.waterStill = (new  BlockFlowing(8, MaterialRegistry.water)).setHardness(100.0).setLightOpacity(3).setBlockName("water");
		Block.waterMoving = (new  BlockStationary(9, MaterialRegistry.water)).setHardness(100.0).setLightOpacity(3).setBlockName("water");
		Block.lavaStill = (new  BlockFlowing(10, MaterialRegistry.lava)).setHardness(0.0).setLightValue(1.0).setLightOpacity(255).setBlockName("lava");
		Block.lavaMoving = (new  BlockStationary(11, MaterialRegistry.lava)).setHardness(100.0).setLightValue(1.0).setLightOpacity(255).setBlockName("lava");
		Block.sand = (new  BlockSand(12, 18)).setHardness(0.5).setStepSound(Block.soundSandFootstep).setBlockName("sand");
		Block.gravel = (new  BlockGravel(13, 19)).setHardness(0.6).setStepSound(Block.soundGravelFootstep).setBlockName("gravel");
		Block.oreGold = (new  BlockOre(14, 32)).setHardness(3.0).setResistance(5.0).setStepSound(Block.soundStoneFootstep).setBlockName("oreGold");
		Block.oreIron = (new  BlockOre(15, 33)).setHardness(3.0).setResistance(5.0).setStepSound(Block.soundStoneFootstep).setBlockName("oreIron");
		Block.oreCoal = (new  BlockOre(16, 34)).setHardness(3.0).setResistance(5.0).setStepSound(Block.soundStoneFootstep).setBlockName("oreCoal");
		Block.wood = (new  BlockLog(17)).setHardness(2.0).setStepSound(Block.soundWoodFootstep).setBlockName("log");
		Block.leaves = (new  BlockLeaves(18, 52)).setHardness(0.2).setLightOpacity(1).setStepSound(Block.soundGrassFootstep).setBlockName("leaves") as BlockLeaves;
		Block.sponge = (new  BlockSponge(19)).setHardness(0.6).setStepSound(Block.soundGrassFootstep).setBlockName("sponge");
		Block.glass = (new  BlockGlass(20, 49, MaterialRegistry.glass, false)).setHardness(0.3).setStepSound(Block.soundGlassFootstep).setBlockName("glass");
		Block.oreLapis = (new  BlockOre(21, 160)).setHardness(3.0).setResistance(5.0).setStepSound(Block.soundStoneFootstep).setBlockName("oreLapis");
		Block.blockLapis = (new  Block(22, 144, MaterialRegistry.rock)).setHardness(3.0).setResistance(5.0).setStepSound(Block.soundStoneFootstep).setBlockName("blockLapis");
		Block.dispenser = (new  BlockDispenser(23)).setHardness(3.5).setStepSound(Block.soundStoneFootstep).setBlockName("dispenser");
		Block.sandStone = (new  BlockSandStone(24)).setStepSound(Block.soundStoneFootstep).setHardness(0.8).setBlockName("sandStone");
		Block.musicBlock = (new  BlockNote(25)).setHardness(0.8).setBlockName("musicBlock");
		Block.field_9262_S = undefined;
		Block.field_9261_T = undefined;
		Block.field_9260_U = undefined;
		Block.field_9259_V = undefined;
		Block.field_9258_W = undefined;
		Block.field_9257_X = undefined;
		Block.field_9256_Y = undefined;
		Block.field_9255_Z = undefined;
		Block.field_9269_aa = undefined;
		Block.cloth = (new  BlockCloth()).setHardness(0.8).setStepSound(Block.soundClothFootstep).setBlockName("cloth");
		Block.field_9268_ac = undefined;
		Block.plantYellow = (new  BlockFlower(37, 13)).setHardness(0.0).setStepSound(Block.soundGrassFootstep).setBlockName("flower") as BlockFlower;
		Block.plantRed = (new  BlockFlower(38, 12)).setHardness(0.0).setStepSound(Block.soundGrassFootstep).setBlockName("rose") as BlockFlower;
		Block.mushroomBrown = (new  BlockMushroom(39, 29)).setHardness(0.0).setStepSound(Block.soundGrassFootstep).setLightValue(0.125).setBlockName("mushroom") as BlockFlower;
		Block.mushroomRed = (new  BlockMushroom(40, 28)).setHardness(0.0).setStepSound(Block.soundGrassFootstep).setBlockName("mushroom") as BlockFlower;
		Block.blockGold = (new  BlockOreBlock(41, 23)).setHardness(3.0).setResistance(10.0).setStepSound(Block.soundMetalFootstep).setBlockName("blockGold");
		Block.blockSteel = (new  BlockOreBlock(42, 22)).setHardness(5.0).setResistance(10.0).setStepSound(Block.soundMetalFootstep).setBlockName("blockIron");
		Block.stairDouble = (new  BlockStep(43, true)).setHardness(2.0).setResistance(10.0).setStepSound(Block.soundStoneFootstep).setBlockName("stoneSlab");
		Block.stairSingle = (new  BlockStep(44, false)).setHardness(2.0).setResistance(10.0).setStepSound(Block.soundStoneFootstep).setBlockName("stoneSlab");
		Block.brick = (new  Block(45, 7, MaterialRegistry.rock)).setHardness(2.0).setResistance(10.0).setStepSound(Block.soundStoneFootstep).setBlockName("brick");
		Block.tnt = (new  BlockTNT(46, 8)).setHardness(0.0).setStepSound(Block.soundGrassFootstep).setBlockName("tnt");
		Block.bookShelf = (new  BlockBookshelf(47, 35)).setHardness(1.5).setStepSound(Block.soundWoodFootstep).setBlockName("bookshelf");
		Block.cobblestoneMossy = (new  Block(48, 36, MaterialRegistry.rock)).setHardness(2.0).setResistance(10.0).setStepSound(Block.soundStoneFootstep).setBlockName("stoneMoss");
		Block.obsidian = (new  BlockObsidian(49, 37)).setHardness(10.0).setResistance(2000.0).setStepSound(Block.soundStoneFootstep).setBlockName("obsidian");
		Block.torchWood = (new  BlockTorch(50, 80)).setHardness(0.0).setLightValue(0.9375).setStepSound(Block.soundWoodFootstep).setBlockName("torch");
		Block.fire = (new  BlockFire(51, 31)).setHardness(0.0).setLightValue(1.0).setStepSound(Block.soundWoodFootstep).setBlockName("fire") as BlockFire;
		Block.mobSpawner = (new  BlockMobSpawner(52, 65)).setHardness(5.0).setStepSound(Block.soundMetalFootstep).setBlockName("mobSpawner");
		Block.stairCompactPlanks = (new  BlockStairs(53, Block.planks)).setBlockName("stairsWood");
		Block.crate = (new  BlockChest(54)).setHardness(2.5).setStepSound(Block.soundWoodFootstep).setBlockName("chest");
		Block.redstoneWire = (new  BlockRedstoneWire(55, 84)).setHardness(0.0).setStepSound(Block.soundPowderFootstep).setBlockName("redstoneDust");
		Block.oreDiamond = (new  BlockOre(56, 50)).setHardness(3.0).setResistance(5.0).setStepSound(Block.soundStoneFootstep).setBlockName("oreDiamond");
		Block.blockDiamond = (new  BlockOreBlock(57, 24)).setHardness(5.0).setResistance(10.0).setStepSound(Block.soundMetalFootstep).setBlockName("blockDiamond");
		Block.workbench = (new  BlockWorkbench(58)).setHardness(2.5).setStepSound(Block.soundWoodFootstep).setBlockName("workbench");
		Block.crops = (new  BlockCrops(59, 88)).setHardness(0.0).setStepSound(Block.soundGrassFootstep).setBlockName("crops");
		Block.tilledField = (new  BlockSoil(60)).setHardness(0.6).setStepSound(Block.soundGravelFootstep).setBlockName("farmland");
		Block.stoneOvenIdle = (new  BlockFurnace(61, false)).setHardness(3.5).setStepSound(Block.soundStoneFootstep).setBlockName("furnace");
		Block.stoneOvenActive = (new  BlockFurnace(62, true)).setHardness(3.5).setStepSound(Block.soundStoneFootstep).setLightValue(0.875).setBlockName("furnace");
		Block.signPost = (new  BlockSign(63, 'Sign', true)).setHardness(1.0).setStepSound(Block.soundWoodFootstep).setBlockName("sign");
		Block.doorWood = (new  BlockDoor(64, MaterialRegistry.wood)).setHardness(3.0).setStepSound(Block.soundWoodFootstep).setBlockName("doorWood");
		Block.ladder = (new  BlockLadder(65, 83)).setHardness(0.4).setStepSound(Block.soundWoodFootstep).setBlockName("ladder");
		Block.minecartTrack = (new  BlockMinecartTrack(66, 128)).setHardness(0.7).setStepSound(Block.soundMetalFootstep).setBlockName("rail");
		Block.stairCompactCobblestone = (new  BlockStairs(67, Block.cobblestone)).setBlockName("stairsStone");
		Block.signWall = (new  BlockSign(68, 'Sign', false)).setHardness(1.0).setStepSound(Block.soundWoodFootstep).setBlockName("sign");
		Block.lever = (new  BlockLever(69, 96)).setHardness(0.5).setStepSound(Block.soundWoodFootstep).setBlockName("lever");
		Block.pressurePlateStone = (new  BlockPressurePlate(70, Block.stone.blockIndexInTexture, EnumMobType.mobs)).setHardness(0.5).setStepSound(Block.soundStoneFootstep).setBlockName("pressurePlate");
		Block.doorSteel = (new  BlockDoor(71, MaterialRegistry.iron)).setHardness(5.0).setStepSound(Block.soundMetalFootstep).setBlockName("doorIron");
		Block.pressurePlatePlanks = (new  BlockPressurePlate(72, Block.planks.blockIndexInTexture, EnumMobType.everything)).setHardness(0.5).setStepSound(Block.soundWoodFootstep).setBlockName("pressurePlate");
		Block.oreRedstone = (new  BlockRedstoneOre(73, 51, false)).setHardness(3.0).setResistance(5.0).setStepSound(Block.soundStoneFootstep).setBlockName("oreRedstone");
		Block.oreRedstoneGlowing = (new  BlockRedstoneOre(74, 51, true)).setLightValue(0.625).setHardness(3.0).setResistance(5.0).setStepSound(Block.soundStoneFootstep).setBlockName("oreRedstone");
		Block.torchRedstoneIdle = (new  BlockRedstoneTorch(75, 115, false)).setHardness(0.0).setStepSound(Block.soundWoodFootstep).setBlockName("notGate");
		Block.torchRedstoneActive = (new  BlockRedstoneTorch(76, 99, true)).setHardness(0.0).setLightValue(0.5).setStepSound(Block.soundWoodFootstep).setBlockName("notGate");
		Block.button = (new  BlockButton(77, Block.stone.blockIndexInTexture)).setHardness(0.5).setStepSound(Block.soundStoneFootstep).setBlockName("button");
		Block.snow = (new  BlockSnow(78, 66)).setHardness(0.1).setStepSound(Block.soundClothFootstep).setBlockName("snow");
		Block.ice = (new  BlockIce(79, 67)).setHardness(0.5).setLightOpacity(3).setStepSound(Block.soundGlassFootstep).setBlockName("ice");
		Block.blockSnow = (new  BlockSnowBlock(80, 66)).setHardness(0.2).setStepSound(Block.soundClothFootstep).setBlockName("snow");
		Block.cactus = (new  BlockCactus(81, 70)).setHardness(0.4).setStepSound(Block.soundClothFootstep).setBlockName("cactus");
		Block.blockClay = (new  BlockClay(82, 72)).setHardness(0.6).setStepSound(Block.soundGravelFootstep).setBlockName("clay");
		Block.reed = (new  BlockReed(83, 73)).setHardness(0.0).setStepSound(Block.soundGrassFootstep).setBlockName("reeds");
		Block.jukebox = (new  BlockJukeBox(84, 74)).setHardness(2.0).setResistance(10.0).setStepSound(Block.soundStoneFootstep).setBlockName("jukebox");
		Block.fence = (new  BlockFence(85, 4)).setHardness(2.0).setResistance(5.0).setStepSound(Block.soundWoodFootstep).setBlockName("fence");
		Block.pumpkin = (new  BlockPumpkin(86, 102, false)).setHardness(1.0).setStepSound(Block.soundWoodFootstep).setBlockName("pumpkin");
		Block.bloodStone = (new  BlockBloodStone(87, 103)).setHardness(0.4).setStepSound(Block.soundStoneFootstep).setBlockName("hellrock");
		Block.slowSand = (new  BlockSlowSand(88, 104)).setHardness(0.5).setStepSound(Block.soundSandFootstep).setBlockName("hellsand");
		Block.lightStone = (new  BlockLightStone(89, 105, MaterialRegistry.glass)).setHardness(0.3).setStepSound(Block.soundGlassFootstep).setLightValue(1.0).setBlockName("lightgem");
		Block.portal = (new  BlockPortal(90, 14)).setHardness(-1.0).setStepSound(Block.soundGlassFootstep).setLightValue(0.75).setBlockName("portal") as BlockPortal;
		Block.pumpkinLantern = (new  BlockPumpkin(91, 102, true)).setHardness(1.0).setStepSound(Block.soundWoodFootstep).setLightValue(1.0).setBlockName("litpumpkin");
		Block.cake = (new  BlockCake(92, 121)).setHardness(0.5).setStepSound(Block.soundClothFootstep).setBlockName("cake");

		// static {
		Item.itemsList[Block.cloth.blockID] = (new  ItemCloth(Block.cloth.blockID - 256)).setItemName("cloth");
		Item.itemsList[Block.wood.blockID] = (new  ItemLog(Block.wood.blockID - 256)).setItemName("log");

		for(let  i0: number = 0; i0 < 256; ++i0) {
			if(Block.blocksList[i0] !== undefined && Item.itemsList[i0] === undefined) {
				Item.itemsList[i0] = new  ItemBlock(i0 - 256);
			}
		}

		Block.itemStackCtor = (a1, a2, a3) => new ItemStack(a1, a2, a3);
		Block.entityItemCtor = (a1, a2, a3, a4, a5) => new EntityItem(a1, a2, a3, a4, a5 as ItemStack)
	// }
	}
}