import { EnumToolMaterial } from "../EnumToolMaterial";
import { Item } from "../Item";
import { ItemArmor } from "../ItemArmor";
import { ItemAxe } from "../ItemAxe";
import { ItemBow } from "../ItemBow";
import { ItemCoal } from "../ItemCoal";
import { ItemFlintAndSteel } from "../ItemFlintAndSteel";
import { ItemFood } from "../ItemFood";
import { ItemHoe } from "../ItemHoe";
import { ItemPickaxe } from "../ItemPickaxe";
import { ItemSeeds } from "../ItemSeeds";
import { ItemSoup } from "../ItemSoup";
import { ItemSpade } from "../ItemSpade";
import { ItemSword } from "../ItemSword";
import { ItemPainting } from "../ItemPainting";
import { ItemSign } from "../ItemSign";
import { ItemDoor } from "../ItemDoor";
import { MaterialRegistry } from "./MaterialRegistry";
import { ItemBucket } from "../ItemBucket";
import { ItemMinecart } from "../ItemMinecart";
import { ItemSaddle } from "../ItemSaddle";
import { ItemRedstone } from "../ItemRedstone";
import { ItemSnowball } from "../ItemSnowball";
import { ItemBoat } from "../ItemBoat";
import { ItemReed } from "../ItemReed";
import { ItemEgg } from "../ItemEgg";
import { ItemFishingRod } from "../ItemFishingRod";
import { ItemDye } from "../ItemDye";
import { ItemRecord } from "../ItemRecord";
import { Block } from "../Block";

export  class ItemRegistry {
    static {
        Item.shovelSteel = (new  ItemSpade(0, EnumToolMaterial.IRON)).setIconCoord(2, 5).setItemName("shovelIron");
        Item.pickaxeSteel = (new  ItemPickaxe(1, EnumToolMaterial.IRON)).setIconCoord(2, 6).setItemName("pickaxeIron");
        Item.axeSteel = (new  ItemAxe(2, EnumToolMaterial.IRON)).setIconCoord(2, 7).setItemName("hatchetIron");
        Item.flintAndSteel = (new  ItemFlintAndSteel(3)).setIconCoord(5, 0).setItemName("flintAndSteel");
        Item.appleRed = (new  ItemFood(4, 4)).setIconCoord(10, 0).setItemName("apple");
        Item.bow = (new  ItemBow(5)).setIconCoord(5, 1).setItemName("bow");
        Item.arrow = (new  Item(6)).setIconCoord(5, 2).setItemName("arrow");
        Item.coal = (new  ItemCoal(7)).setIconCoord(7, 0).setItemName("coal");
        Item.diamond = (new  Item(8)).setIconCoord(7, 3).setItemName("emerald");
        Item.ingotIron = (new  Item(9)).setIconCoord(7, 1).setItemName("ingotIron");
        Item.ingotGold = (new  Item(10)).setIconCoord(7, 2).setItemName("ingotGold");
        Item.swordSteel = (new  ItemSword(11, EnumToolMaterial.IRON)).setIconCoord(2, 4).setItemName("swordIron");
        Item.swordWood = (new  ItemSword(12, EnumToolMaterial.WOOD)).setIconCoord(0, 4).setItemName("swordWood");
        Item.shovelWood = (new  ItemSpade(13, EnumToolMaterial.WOOD)).setIconCoord(0, 5).setItemName("shovelWood");
        Item.pickaxeWood = (new  ItemPickaxe(14, EnumToolMaterial.WOOD)).setIconCoord(0, 6).setItemName("pickaxeWood");
        Item.axeWood = (new  ItemAxe(15, EnumToolMaterial.WOOD)).setIconCoord(0, 7).setItemName("hatchetWood");
        Item.swordStone = (new  ItemSword(16, EnumToolMaterial.STONE)).setIconCoord(1, 4).setItemName("swordStone");
        Item.shovelStone = (new  ItemSpade(17, EnumToolMaterial.STONE)).setIconCoord(1, 5).setItemName("shovelStone");
        Item.pickaxeStone = (new  ItemPickaxe(18, EnumToolMaterial.STONE)).setIconCoord(1, 6).setItemName("pickaxeStone");
        Item.axeStone = (new  ItemAxe(19, EnumToolMaterial.STONE)).setIconCoord(1, 7).setItemName("hatchetStone");
        Item.swordDiamond = (new  ItemSword(20, EnumToolMaterial.EMERALD)).setIconCoord(3, 4).setItemName("swordDiamond");
        Item.shovelDiamond = (new  ItemSpade(21, EnumToolMaterial.EMERALD)).setIconCoord(3, 5).setItemName("shovelDiamond");
        Item.pickaxeDiamond = (new  ItemPickaxe(22, EnumToolMaterial.EMERALD)).setIconCoord(3, 6).setItemName("pickaxeDiamond");
        Item.axeDiamond = (new  ItemAxe(23, EnumToolMaterial.EMERALD)).setIconCoord(3, 7).setItemName("hatchetDiamond");
        Item.stick = (new  Item(24)).setIconCoord(5, 3).setFull3D().setItemName("stick");
        Item.bowlEmpty = (new  Item(25)).setIconCoord(7, 4).setItemName("bowl");
        Item.bowlSoup = (new  ItemSoup(26, 10)).setIconCoord(8, 4).setItemName("mushroomStew");
        Item.swordGold = (new  ItemSword(27, EnumToolMaterial.GOLD)).setIconCoord(4, 4).setItemName("swordGold");
        Item.shovelGold = (new  ItemSpade(28, EnumToolMaterial.GOLD)).setIconCoord(4, 5).setItemName("shovelGold");
        Item.pickaxeGold = (new  ItemPickaxe(29, EnumToolMaterial.GOLD)).setIconCoord(4, 6).setItemName("pickaxeGold");
        Item.axeGold = (new  ItemAxe(30, EnumToolMaterial.GOLD)).setIconCoord(4, 7).setItemName("hatchetGold");
        Item.silk = (new  Item(31)).setIconCoord(8, 0).setItemName("string");
        Item.feather = (new  Item(32)).setIconCoord(8, 1).setItemName("feather");
        Item.gunpowder = (new  Item(33)).setIconCoord(8, 2).setItemName("sulphur");
        Item.hoeWood = (new  ItemHoe(34, EnumToolMaterial.WOOD)).setIconCoord(0, 8).setItemName("hoeWood");
        Item.hoeStone = (new  ItemHoe(35, EnumToolMaterial.STONE)).setIconCoord(1, 8).setItemName("hoeStone");
        Item.hoeSteel = (new  ItemHoe(36, EnumToolMaterial.IRON)).setIconCoord(2, 8).setItemName("hoeIron");
        Item.hoeDiamond = (new  ItemHoe(37, EnumToolMaterial.EMERALD)).setIconCoord(3, 8).setItemName("hoeDiamond");
        Item.hoeGold = (new  ItemHoe(38, EnumToolMaterial.GOLD)).setIconCoord(4, 8).setItemName("hoeGold");
        Item.seeds = (new  ItemSeeds(39, Block.crops.blockID)).setIconCoord(9, 0).setItemName("seeds");
        Item.wheat = (new  Item(40)).setIconCoord(9, 1).setItemName("wheat");
        Item.bread = (new  ItemFood(41, 5)).setIconCoord(9, 2).setItemName("bread");
        Item.helmetLeather = (new  ItemArmor(42, 0, 0, 0)).setIconCoord(0, 0).setItemName("helmetCloth");
        Item.plateLeather = (new  ItemArmor(43, 0, 0, 1)).setIconCoord(0, 1).setItemName("chestplateCloth");
        Item.legsLeather = (new  ItemArmor(44, 0, 0, 2)).setIconCoord(0, 2).setItemName("leggingsCloth");
        Item.bootsLeather = (new  ItemArmor(45, 0, 0, 3)).setIconCoord(0, 3).setItemName("bootsCloth");
        Item.helmetChain = (new  ItemArmor(46, 1, 1, 0)).setIconCoord(1, 0).setItemName("helmetChain");
        Item.plateChain = (new  ItemArmor(47, 1, 1, 1)).setIconCoord(1, 1).setItemName("chestplateChain");
        Item.legsChain = (new  ItemArmor(48, 1, 1, 2)).setIconCoord(1, 2).setItemName("leggingsChain");
        Item.bootsChain = (new  ItemArmor(49, 1, 1, 3)).setIconCoord(1, 3).setItemName("bootsChain");
        Item.helmetSteel = (new  ItemArmor(50, 2, 2, 0)).setIconCoord(2, 0).setItemName("helmetIron");
        Item.plateSteel = (new  ItemArmor(51, 2, 2, 1)).setIconCoord(2, 1).setItemName("chestplateIron");
        Item.legsSteel = (new  ItemArmor(52, 2, 2, 2)).setIconCoord(2, 2).setItemName("leggingsIron");
        Item.bootsSteel = (new  ItemArmor(53, 2, 2, 3)).setIconCoord(2, 3).setItemName("bootsIron");
        Item.helmetDiamond = (new  ItemArmor(54, 3, 3, 0)).setIconCoord(3, 0).setItemName("helmetDiamond");
        Item.plateDiamond = (new  ItemArmor(55, 3, 3, 1)).setIconCoord(3, 1).setItemName("chestplateDiamond");
        Item.legsDiamond = (new  ItemArmor(56, 3, 3, 2)).setIconCoord(3, 2).setItemName("leggingsDiamond");
        Item.bootsDiamond = (new  ItemArmor(57, 3, 3, 3)).setIconCoord(3, 3).setItemName("bootsDiamond");
        Item.helmetGold = (new  ItemArmor(58, 1, 4, 0)).setIconCoord(4, 0).setItemName("helmetGold");
        Item.plateGold = (new  ItemArmor(59, 1, 4, 1)).setIconCoord(4, 1).setItemName("chestplateGold");
        Item.legsGold = (new  ItemArmor(60, 1, 4, 2)).setIconCoord(4, 2).setItemName("leggingsGold");
        Item.bootsGold = (new  ItemArmor(61, 1, 4, 3)).setIconCoord(4, 3).setItemName("bootsGold");
        Item.flint = (new  Item(62)).setIconCoord(6, 0).setItemName("flint");
        Item.porkRaw = (new  ItemFood(63, 3)).setIconCoord(7, 5).setItemName("porkchopRaw");
        Item.porkCooked = (new  ItemFood(64, 8)).setIconCoord(8, 5).setItemName("porkchopCooked");
        Item.painting = (new  ItemPainting(65)).setIconCoord(10, 1).setItemName("painting");
        Item.appleGold = (new  ItemFood(66, 42)).setIconCoord(11, 0).setItemName("appleGold");
        Item.sign = (new  ItemSign(67)).setIconCoord(10, 2).setItemName("sign");
        Item.doorWood = (new  ItemDoor(68, MaterialRegistry.wood)).setIconCoord(11, 2).setItemName("doorWood");
        Item.bucketEmpty = (new  ItemBucket(69, 0)).setIconCoord(10, 4).setItemName("bucket");
        Item.bucketWater = (new  ItemBucket(70, Block.waterStill.blockID)).setIconCoord(11, 4).setItemName("bucketWater").setContainerItem(Item.bucketEmpty);
        Item.bucketLava = (new  ItemBucket(71, Block.lavaStill.blockID)).setIconCoord(12, 4).setItemName("bucketLava").setContainerItem(Item.bucketEmpty);
        Item.minecartEmpty = (new  ItemMinecart(72, 0)).setIconCoord(7, 8).setItemName("minecart");
        Item.saddle = (new  ItemSaddle(73)).setIconCoord(8, 6).setItemName("saddle");
        Item.doorSteel = (new  ItemDoor(74, MaterialRegistry.iron)).setIconCoord(12, 2).setItemName("doorIron");
        Item.redstone = (new  ItemRedstone(75)).setIconCoord(8, 3).setItemName("redstone");
        Item.snowball = (new  ItemSnowball(76)).setIconCoord(14, 0).setItemName("snowball");
        Item.boat = (new  ItemBoat(77)).setIconCoord(8, 8).setItemName("boat");
        Item.leather = (new  Item(78)).setIconCoord(7, 6).setItemName("leather");
        Item.bucketMilk = (new  ItemBucket(79, -1)).setIconCoord(13, 4).setItemName("milk").setContainerItem(Item.bucketEmpty);
        Item.brick = (new  Item(80)).setIconCoord(6, 1).setItemName("brick");
        Item.clay = (new  Item(81)).setIconCoord(9, 3).setItemName("clay");
        Item.reed = (new  ItemReed(82, Block.reed)).setIconCoord(11, 1).setItemName("reeds");
        Item.paper = (new  Item(83)).setIconCoord(10, 3).setItemName("paper");
        Item.book = (new  Item(84)).setIconCoord(11, 3).setItemName("book");
        Item.slimeBall = (new  Item(85)).setIconCoord(14, 1).setItemName("slimeball");
        Item.minecartCrate = (new  ItemMinecart(86, 1)).setIconCoord(7, 9).setItemName("minecartChest");
        Item.minecartPowered = (new  ItemMinecart(87, 2)).setIconCoord(7, 10).setItemName("minecartFurnace");
        Item.egg = (new  ItemEgg(88)).setIconCoord(12, 0).setItemName("egg");
        Item.compass = (new  Item(89)).setIconCoord(6, 3).setItemName("compass");
        Item.fishingRod = (new  ItemFishingRod(90)).setIconCoord(5, 4).setItemName("fishingRod");
        Item.pocketSundial = (new  Item(91)).setIconCoord(6, 4).setItemName("clock");
        Item.lightStoneDust = (new  Item(92)).setIconCoord(9, 4).setItemName("yellowDust");
        Item.fishRaw = (new  ItemFood(93, 2)).setIconCoord(9, 5).setItemName("fishRaw");
        Item.fishCooked = (new  ItemFood(94, 5)).setIconCoord(10, 5).setItemName("fishCooked");
        Item.dyePowder = (new  ItemDye(95)).setIconCoord(14, 4).setItemName("dyePowder");
        Item.bone = (new  Item(96)).setIconCoord(12, 1).setItemName("bone").setFull3D();
        Item.sugar = (new  Item(97)).setIconCoord(13, 0).setItemName("sugar").setFull3D();
        Item.cake = (new  ItemReed(98, Block.cake)).setMaxStackSize(1).setIconCoord(13, 1).setItemName("cake");
        Item.record13 = (new  ItemRecord(2000, "13")).setIconCoord(0, 15).setItemName("record");
        Item.recordCat = (new  ItemRecord(2001, "cat")).setIconCoord(1, 15).setItemName("record");
    }
}
